name: get_fit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  pin_code_fields: any
  vertical_card_pager: any
  animated_weight_picker: any
  omni_datetime_picker: any
  payment_card: any
  flutter_svg: ^2.0.9
  supabase_flutter: ^1.10.25
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.7
  pdf: ^3.10.0
  share_plus: ^7.2.0
  path_provider: ^2.1.0
  video_player: ^2.9.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  flutter_stripe: ^10.1.1
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  agora_rtc_engine: 6.6.3
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  sign_in_with_apple: ^6.0.0
  ffi: ^2.0.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 26

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/onboarding/
    - assets/launch/
    - assets/auth/
    - assets/home/
    - assets/challenge/
    - assets/icons/