import 'package:flutter/material.dart';

class Exercise {
  final String id;
  final String title;
  final String category;
  final String description;
  final String imageUrl;
  final String sets;
  final String reps;
  final String rest;
  final String level;
  final String duration;
  final String kcal;
  final String exerciseCount;

  const Exercise({
    required this.id,
    required this.title,
    required this.category,
    required this.description,
    required this.imageUrl,
    required this.sets,
    required this.reps,
    required this.rest,
    required this.level,
    this.duration = '30 Minutes',
    this.kcal = '320 Kcal',
    this.exerciseCount = '5 Exercises',
  });
}

final List<Exercise> dummyExercises = [
  Exercise(
    id: 'bench_press',
    title: 'Bench Press',
    category: 'Chest',
    description: 'Classic chest builder targeting pecs, shoulders and triceps.',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600',
    sets: '4 sets',
    reps: '10 reps',
    rest: 'Rest 60s',
    level: 'Intermediate',
    duration: '45 Minutes',
    kcal: '380 Kcal',
    exerciseCount: '4 Exercises',
  ),
  Exercise(
    id: 'squat',
    title: 'Squat',
    category: 'Legs',
    description: 'King of lower-body movements — quads, glutes, core.',
    imageUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600',
    sets: '4 sets',
    reps: '12 reps',
    rest: 'Rest 90s',
    level: 'Beginner',
    duration: '40 Minutes',
    kcal: '420 Kcal',
    exerciseCount: '6 Exercises',
  ),
  Exercise(
    id: 'pull_ups',
    title: 'Pull Ups',
    category: 'Back',
    description: 'Best compound movement for a wide, strong back.',
    imageUrl: 'https://images.pexels.com/photos/4162449/pexels-photo-4162449.jpeg',
    sets: '3 sets',
    reps: '10 reps',
    rest: 'Rest 60s',
    level: 'Advanced',
    duration: '30 Minutes',
    kcal: '310 Kcal',
    exerciseCount: '5 Exercises',
  ),
  Exercise(
    id: 'shoulder_press',
    title: 'Shoulder Press',
    category: 'Shoulders',
    description: 'Press overhead to build full shoulder caps.',
    imageUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600',
    sets: '3 sets',
    reps: '10 reps',
    rest: 'Rest 45s',
    level: 'Intermediate',
    duration: '35 Minutes',
    kcal: '290 Kcal',
    exerciseCount: '4 Exercises',
  ),
  Exercise(
    id: 'bicep_curl',
    title: 'Bicep Curl',
    category: 'Arms',
    description: 'Great exercise for building strength and arm size.',
    imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600',
    sets: '3 sets',
    reps: '10 reps',
    rest: 'Rest 60s',
    level: 'Beginner',
    duration: '25 Minutes',
    kcal: '210 Kcal',
    exerciseCount: '3 Exercises',
  ),
  Exercise(
    id: 'plank',
    title: 'Plank',
    category: 'Core',
    description: 'Isometric core hold — builds anti-rotation stability.',
    imageUrl: 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=600',
    sets: '3 sets',
    reps: '1 rep',
    rest: 'Rest 30s',
    level: 'Beginner',
    duration: '20 Minutes',
    kcal: '180 Kcal',
    exerciseCount: '3 Exercises',
  ),
  Exercise(
    id: 'deadlift',
    title: 'Deadlift',
    category: 'Back',
    description: 'Full body powerhouse — builds total posterior chain strength.',
    imageUrl: 'https://images.unsplash.com/photo-1603287681836-b174ce5074c2?w=600',
    sets: '4 sets',
    reps: '8 reps',
    rest: 'Rest 120s',
    level: 'Advanced',
    duration: '50 Minutes',
    kcal: '520 Kcal',
    exerciseCount: '4 Exercises',
  ),
  Exercise(
    id: 'tricep_dips',
    title: 'Tricep Dips',
    category: 'Arms',
    description: 'Bodyweight move that torches the triceps effectively.',
    imageUrl: 'https://images.pexels.com/photos/4162438/pexels-photo-4162438.jpeg',
    sets: '3 sets',
    reps: '15 reps',
    rest: 'Rest 45s',
    level: 'Intermediate',
    duration: '25 Minutes',
    kcal: '230 Kcal',
    exerciseCount: '3 Exercises',
  ),
  Exercise(
    id: 'hammer_curl',
    title: 'Hammer Curl',
    category: 'Arms',
    description: 'Neutral grip curl targeting brachialis and forearms.',
    imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600',
    sets: '3 sets',
    reps: '12 reps',
    rest: 'Rest 45s',
    level: 'Beginner',
    duration: '20 Minutes',
    kcal: '190 Kcal',
    exerciseCount: '3 Exercises',
  ),
  Exercise(
    id: 'tricep_pushdown',
    title: 'Tricep Pushdown',
    category: 'Arms',
    description: 'Cable exercise isolating the triceps for maximum pump.',
    imageUrl: 'https://images.pexels.com/photos/4162449/pexels-photo-4162449.jpeg',
    sets: '4 sets',
    reps: '12 reps',
    rest: 'Rest 45s',
    level: 'Beginner',
    duration: '25 Minutes',
    kcal: '200 Kcal',
    exerciseCount: '3 Exercises',
  ),
  Exercise(
    id: 'preacher_curl',
    title: 'Preacher Curl',
    category: 'Arms',
    description: 'Isolates the bicep peak by removing shoulder involvement.',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600',
    sets: '3 sets',
    reps: '10 reps',
    rest: 'Rest 60s',
    level: 'Intermediate',
    duration: '25 Minutes',
    kcal: '210 Kcal',
    exerciseCount: '3 Exercises',
  ),
  Exercise(
    id: 'overhead_tricep_extension',
    title: 'Overhead Tricep Extension',
    category: 'Arms',
    description: 'Stretches and contracts the long head of the tricep fully.',
    imageUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600',
    sets: '3 sets',
    reps: '12 reps',
    rest: 'Rest 45s',
    level: 'Intermediate',
    duration: '20 Minutes',
    kcal: '195 Kcal',
    exerciseCount: '3 Exercises',
  ),
  Exercise(
    id: 'concentration_curl',
    title: 'Concentration Curl',
    category: 'Arms',
    description: 'Seated isolation curl for maximum bicep peak contraction.',
    imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600',
    sets: '3 sets',
    reps: '10 reps',
    rest: 'Rest 45s',
    level: 'Beginner',
    duration: '20 Minutes',
    kcal: '180 Kcal',
    exerciseCount: '3 Exercises',
  ),
  Exercise(
    id: 'skull_crushers',
    title: 'Skull Crushers',
    category: 'Arms',
    description: 'Lying tricep extension that builds serious arm mass.',
    imageUrl: 'https://images.pexels.com/photos/4162438/pexels-photo-4162438.jpeg',
    sets: '4 sets',
    reps: '10 reps',
    rest: 'Rest 60s',
    level: 'Advanced',
    duration: '30 Minutes',
    kcal: '240 Kcal',
    exerciseCount: '4 Exercises',
  ),
  Exercise(
    id: 'cable_curl',
    title: 'Cable Curl',
    category: 'Arms',
    description: 'Constant tension curl using cable for full range activation.',
    imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600',
    sets: '3 sets',
    reps: '15 reps',
    rest: 'Rest 45s',
    level: 'Intermediate',
    duration: '25 Minutes',
    kcal: '205 Kcal',
    exerciseCount: '3 Exercises',
  ),
  Exercise(
    id: 'reverse_curl',
    title: 'Reverse Curl',
    category: 'Arms',
    description: 'Overhand grip curl targeting brachioradialis and forearms.',
    imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600',
    sets: '3 sets',
    reps: '12 reps',
    rest: 'Rest 45s',
    level: 'Beginner',
    duration: '20 Minutes',
    kcal: '185 Kcal',
    exerciseCount: '3 Exercises',
  ),
// CHEST
  Exercise(id: 'incline_press', title: 'Incline Bench Press', category: 'Chest', description: 'Upper chest builder using an inclined bench angle.', imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600', sets: '4 sets', reps: '10 reps', rest: 'Rest 60s', level: 'Intermediate', duration: '40 Minutes', kcal: '350 Kcal', exerciseCount: '4 Exercises'),
  Exercise(id: 'chest_fly', title: 'Dumbbell Fly', category: 'Chest', description: 'Wide arc movement that stretches and contracts the pecs.', imageUrl: 'https://images.pexels.com/photos/4162449/pexels-photo-4162449.jpeg', sets: '3 sets', reps: '12 reps', rest: 'Rest 45s', level: 'Beginner', duration: '30 Minutes', kcal: '280 Kcal', exerciseCount: '3 Exercises'),
  Exercise(id: 'push_up', title: 'Push Up', category: 'Chest', description: 'Bodyweight classic that builds chest, shoulders and triceps.', imageUrl: 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=600', sets: '4 sets', reps: '20 reps', rest: 'Rest 30s', level: 'Beginner', duration: '25 Minutes', kcal: '220 Kcal', exerciseCount: '3 Exercises'),
  Exercise(id: 'cable_crossover', title: 'Cable Crossover', category: 'Chest', description: 'Cable fly for constant tension across the full chest.', imageUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600', sets: '3 sets', reps: '15 reps', rest: 'Rest 45s', level: 'Intermediate', duration: '35 Minutes', kcal: '300 Kcal', exerciseCount: '4 Exercises'),
  Exercise(id: 'decline_press', title: 'Decline Press', category: 'Chest', description: 'Lower chest emphasis using a declined bench position.', imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600', sets: '4 sets', reps: '10 reps', rest: 'Rest 60s', level: 'Advanced', duration: '40 Minutes', kcal: '370 Kcal', exerciseCount: '4 Exercises'),
  Exercise(id: 'chest_dip', title: 'Chest Dip', category: 'Chest', description: 'Bodyweight dip leaning forward to target lower chest.', imageUrl: 'https://images.pexels.com/photos/4162438/pexels-photo-4162438.jpeg', sets: '3 sets', reps: '12 reps', rest: 'Rest 45s', level: 'Intermediate', duration: '30 Minutes', kcal: '260 Kcal', exerciseCount: '3 Exercises'),
  Exercise(id: 'pec_deck', title: 'Pec Deck Machine', category: 'Chest', description: 'Machine fly isolating the pectoral muscles safely.', imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600', sets: '3 sets', reps: '15 reps', rest: 'Rest 45s', level: 'Beginner', duration: '25 Minutes', kcal: '240 Kcal', exerciseCount: '3 Exercises'),

  // BACK
  Exercise(id: 'bent_over_row', title: 'Bent Over Row', category: 'Back', description: 'Barbell row for thickness across the entire back.', imageUrl: 'https://images.unsplash.com/photo-1603287681836-b174ce5074c2?w=600', sets: '4 sets', reps: '10 reps', rest: 'Rest 60s', level: 'Intermediate', duration: '40 Minutes', kcal: '390 Kcal', exerciseCount: '4 Exercises'),
  Exercise(id: 'lat_pulldown', title: 'Lat Pulldown', category: 'Back', description: 'Cable pulldown building wide lats for a V-taper.', imageUrl: 'https://images.pexels.com/photos/4162449/pexels-photo-4162449.jpeg', sets: '4 sets', reps: '12 reps', rest: 'Rest 45s', level: 'Beginner', duration: '35 Minutes', kcal: '310 Kcal', exerciseCount: '4 Exercises'),
  Exercise(id: 'seated_row', title: 'Seated Cable Row', category: 'Back', description: 'Horizontal pull targeting mid-back and rhomboids.', imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600', sets: '3 sets', reps: '12 reps', rest: 'Rest 45s', level: 'Beginner', duration: '30 Minutes', kcal: '280 Kcal', exerciseCount: '3 Exercises'),
  Exercise(id: 'face_pull', title: 'Face Pull', category: 'Back', description: 'Rear delt and upper back cable exercise for posture.', imageUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600', sets: '3 sets', reps: '15 reps', rest: 'Rest 30s', level: 'Beginner', duration: '25 Minutes', kcal: '220 Kcal', exerciseCount: '3 Exercises'),
  Exercise(id: 'single_arm_row', title: 'Single Arm Row', category: 'Back', description: 'Dumbbell row for unilateral back strength and balance.', imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600', sets: '3 sets', reps: '10 reps', rest: 'Rest 45s', level: 'Intermediate', duration: '30 Minutes', kcal: '290 Kcal', exerciseCount: '3 Exercises'),
  Exercise(id: 'hyperextension', title: 'Back Extension', category: 'Back', description: 'Lower back and erector spinae isolation movement.', imageUrl: 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=600', sets: '3 sets', reps: '15 reps', rest: 'Rest 30s', level: 'Beginner', duration: '20 Minutes', kcal: '200 Kcal', exerciseCount: '3 Exercises'),
  Exercise(id: 'tbar_row', title: 'T-Bar Row', category: 'Back', description: 'Compound row for serious back thickness and density.', imageUrl: 'https://images.pexels.com/photos/4162438/pexels-photo-4162438.jpeg', sets: '4 sets', reps: '8 reps', rest: 'Rest 90s', level: 'Advanced', duration: '45 Minutes', kcal: '430 Kcal', exerciseCount: '4 Exercises'),

  // SHOULDERS
  Exercise(id: 'lateral_raise', title: 'Lateral Raise', category: 'Shoulders', description: 'Side delt isolation for wide, capped shoulders.', imageUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600', sets: '3 sets', reps: '15 reps', rest: 'Rest 30s', level: 'Beginner', duration: '25 Minutes', kcal: '210 Kcal', exerciseCount: '3 Exercises'),
  Exercise(id: 'front_raise', title: 'Front Raise', category: 'Shoulders', description: 'Anterior delt raise for front shoulder definition.', imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600', sets: '3 sets', reps: '12 reps', rest: 'Rest 30s', level: 'Beginner', duration: '20 Minutes', kcal: '190 Kcal', exerciseCount: '3 Exercises'),
  Exercise(id: 'arnold_press', title: 'Arnold Press', category: 'Shoulders', description: 'Rotating dumbbell press hitting all three delt heads.', imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600', sets: '4 sets', reps: '10 reps', rest: 'Rest 60s', level: 'Intermediate', duration: '35 Minutes', kcal: '300 Kcal', exerciseCount: '4 Exercises'),
  Exercise(id: 'upright_row', title: 'Upright Row', category: 'Shoulders', description: 'Barbell pull to chin targeting traps and side delts.', imageUrl: 'https://images.pexels.com/photos/4162449/pexels-photo-4162449.jpeg', sets: '3 sets', reps: '12 reps', rest: 'Rest 45s', level: 'Intermediate', duration: '30 Minutes', kcal: '260 Kcal', exerciseCount: '3 Exercises'),
  Exercise(id: 'shrugs', title: 'Barbell Shrugs', category: 'Shoulders', description: 'Trap builder using heavy barbell shrugging motion.', imageUrl: 'https://images.unsplash.com/photo-1603287681836-b174ce5074c2?w=600', sets: '4 sets', reps: '15 reps', rest: 'Rest 45s', level: 'Beginner', duration: '25 Minutes', kcal: '230 Kcal', exerciseCount: '3 Exercises'),
  Exercise(id: 'rear_delt_fly', title: 'Rear Delt Fly', category: 'Shoulders', description: 'Bent-over fly targeting rear delts and upper back.', imageUrl: 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=600', sets: '3 sets', reps: '15 reps', rest: 'Rest 30s', level: 'Beginner', duration: '20 Minutes', kcal: '200 Kcal', exerciseCount: '3 Exercises'),
  Exercise(id: 'cable_lateral', title: 'Cable Lateral Raise', category: 'Shoulders', description: 'Single cable lateral raise with constant tension.', imageUrl: 'https://images.pexels.com/photos/4162438/pexels-photo-4162438.jpeg', sets: '3 sets', reps: '15 reps', rest: 'Rest 30s', level: 'Intermediate', duration: '25 Minutes', kcal: '215 Kcal', exerciseCount: '3 Exercises'),

  // LEGS
  Exercise(id: 'leg_press', title: 'Leg Press', category: 'Legs', description: 'Machine compound for quads, hamstrings and glutes.', imageUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600', sets: '4 sets', reps: '12 reps', rest: 'Rest 90s', level: 'Beginner', duration: '40 Minutes', kcal: '400 Kcal', exerciseCount: '4 Exercises'),
  Exercise(id: 'romanian_deadlift', title: 'Romanian Deadlift', category: 'Legs', description: 'Hip hinge movement targeting hamstrings and glutes.', imageUrl: 'https://images.unsplash.com/photo-1603287681836-b174ce5074c2?w=600', sets: '4 sets', reps: '10 reps', rest: 'Rest 90s', level: 'Intermediate', duration: '45 Minutes', kcal: '430 Kcal', exerciseCount: '4 Exercises'),
  Exercise(id: 'lunges', title: 'Walking Lunges', category: 'Legs', description: 'Unilateral leg exercise for balance and quad strength.', imageUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600', sets: '3 sets', reps: '12 reps each', rest: 'Rest 60s', level: 'Beginner', duration: '30 Minutes', kcal: '340 Kcal', exerciseCount: '3 Exercises'),
  Exercise(id: 'leg_curl', title: 'Leg Curl', category: 'Legs', description: 'Machine isolation for hamstring strength and size.', imageUrl: 'https://images.pexels.com/photos/4162449/pexels-photo-4162449.jpeg', sets: '3 sets', reps: '12 reps', rest: 'Rest 45s', level: 'Beginner', duration: '25 Minutes', kcal: '260 Kcal', exerciseCount: '3 Exercises'),
  Exercise(id: 'leg_extension', title: 'Leg Extension', category: 'Legs', description: 'Quad isolation machine for definition and strength.', imageUrl: 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=600', sets: '3 sets', reps: '15 reps', rest: 'Rest 45s', level: 'Beginner', duration: '25 Minutes', kcal: '240 Kcal', exerciseCount: '3 Exercises'),
  Exercise(id: 'calf_raise', title: 'Standing Calf Raise', category: 'Legs', description: 'Calf and soleus builder using bodyweight or machine.', imageUrl: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=600', sets: '4 sets', reps: '20 reps', rest: 'Rest 30s', level: 'Beginner', duration: '20 Minutes', kcal: '180 Kcal', exerciseCount: '3 Exercises'),
  Exercise(id: 'bulgarian_split', title: 'Bulgarian Split Squat', category: 'Legs', description: 'Rear foot elevated squat for unilateral leg power.', imageUrl: 'https://images.unsplash.com/photo-1603287681836-b174ce5074c2?w=600', sets: '3 sets', reps: '10 reps each', rest: 'Rest 60s', level: 'Advanced', duration: '40 Minutes', kcal: '410 Kcal', exerciseCount: '4 Exercises'),

  // CORE
  Exercise(id: 'crunches', title: 'Crunches', category: 'Core', description: 'Basic ab crunch for upper abdominal development.', imageUrl: 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=600', sets: '3 sets', reps: '20 reps', rest: 'Rest 30s', level: 'Beginner', duration: '20 Minutes', kcal: '160 Kcal', exerciseCount: '3 Exercises'),
  Exercise(id: 'leg_raise', title: 'Hanging Leg Raise', category: 'Core', description: 'Lower ab and hip flexor exercise hanging from a bar.', imageUrl: 'https://images.pexels.com/photos/4162449/pexels-photo-4162449.jpeg', sets: '3 sets', reps: '12 reps', rest: 'Rest 30s', level: 'Intermediate', duration: '25 Minutes', kcal: '200 Kcal', exerciseCount: '3 Exercises'),
  Exercise(id: 'russian_twist', title: 'Russian Twist', category: 'Core', description: 'Rotational core exercise targeting obliques.', imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=600', sets: '3 sets', reps: '20 reps', rest: 'Rest 30s', level: 'Beginner', duration: '20 Minutes', kcal: '175 Kcal', exerciseCount: '3 Exercises'),
  Exercise(id: 'cable_crunch', title: 'Cable Crunch', category: 'Core', description: 'Weighted ab crunch using cable for resistance.', imageUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=600', sets: '4 sets', reps: '15 reps', rest: 'Rest 30s', level: 'Intermediate', duration: '25 Minutes', kcal: '210 Kcal', exerciseCount: '3 Exercises'),
  Exercise(id: 'ab_wheel', title: 'Ab Wheel Rollout', category: 'Core', description: 'Full core rollout building serious anti-extension strength.', imageUrl: 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=600', sets: '3 sets', reps: '10 reps', rest: 'Rest 45s', level: 'Advanced', duration: '25 Minutes', kcal: '230 Kcal', exerciseCount: '3 Exercises'),
  Exercise(id: 'mountain_climber', title: 'Mountain Climbers', category: 'Core', description: 'Dynamic plank variation for core and cardio conditioning.', imageUrl: 'https://images.pexels.com/photos/4162438/pexels-photo-4162438.jpeg', sets: '3 sets', reps: '30 reps', rest: 'Rest 30s', level: 'Beginner', duration: '20 Minutes', kcal: '190 Kcal', exerciseCount: '3 Exercises'),
  Exercise(id: 'side_plank', title: 'Side Plank', category: 'Core', description: 'Lateral core hold targeting obliques and hip abductors.', imageUrl: 'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?w=600', sets: '3 sets', reps: '1 rep each side', rest: 'Rest 30s', level: 'Beginner', duration: '20 Minutes', kcal: '170 Kcal', exerciseCount: '3 Exercises'),
];